# .github/workflows/ci-dev.yml
name: CI Pipeline - Dev Branch

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  test-and-evaluate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Setup DVC
        uses: iterative/setup-dvc@v1
      
      - name: Pull data and model from DVC
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc remote modify myremote gdrive_use_service_account true
          dvc pull
        continue-on-error: true
      
      - name: Train model (if not pulled from DVC)
        run: |
          if [ ! -f "models/iris_model.pkl" ]; then
            python src/train.py
          fi
      
      - name: Run data validation tests
        run: |
          pytest tests/test_data_validation.py -v --tb=short
      
      - name: Run model evaluation tests
        run: |
          pytest tests/test_model_evaluation.py -v --tb=short
      
      - name: Generate test coverage report
        run: |
          pytest tests/ --cov=src --cov-report=term --cov-report=html
      
      - name: Evaluate model and generate metrics
        run: |
          python src/evaluate.py
      
      - name: Setup CML
        uses: iterative/setup-cml@v1
      
      - name: Create CML Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# Model Evaluation Report - Dev Branch" > report.md
          echo "" >> report.md
          echo "## Test Results" >> report.md
          echo "✅ All tests passed successfully!" >> report.md
          echo "" >> report.md
          
          echo "## Model Performance Metrics" >> report.md
          echo "" >> report.md
          
          if [ -f "metrics/evaluation.json" ]; then
            echo "| Metric | Value |" >> report.md
            echo "|--------|-------|" >> report.md
            cat metrics/evaluation.json | python -c "import sys, json; data = json.load(sys.stdin); [print(f'| {k} | {v:.4f} |') for k, v in data.items()]" >> report.md
          fi
          
          echo "" >> report.md
          echo "## Data Validation" >> report.md
          echo "- ✅ Dataset shape verified" >> report.md
          echo "- ✅ No missing values detected" >> report.md
          echo "- ✅ Feature ranges validated" >> report.md
          echo "- ✅ Class distribution balanced" >> report.md
          echo "" >> report.md
          
          echo "---" >> report.md
          echo "*Generated on: $(date)*" >> report.md
          
          cml comment create report.md
